// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXkEuWTppabzBFBw-9jREiZebqslxC2II',
    appId: '1:136945913684:android:9ea3294884bf72541d02c1',
    messagingSenderId: '136945913684',
    projectId: 'emploiboost',
    databaseURL: 'https://emploiboost-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'emploiboost.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeL9yYoq9KpZY52Ll5Hi9mmTNyo4Q70b4',
    appId: '1:136945913684:ios:bf941dd87e8ac22f1d02c1',
    messagingSenderId: '136945913684',
    projectId: 'emploiboost',
    databaseURL: 'https://emploiboost-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'emploiboost.appspot.com',
    iosClientId: '136945913684-nh1aqr3g59e6rf1iui96iv3ce8ln19m0.apps.googleusercontent.com',
    iosBundleId: 'com.emploiboost.emploiboost',
  );

}
