name: Build iOS
on: [push]

jobs:
  build:
    runs-on: macos-14           # Xcode 15

    steps:
      # 1) Récupère ton code
      - uses: actions/checkout@v4

      # 2) Installe Flutter
      - uses: subosito/flutter-action@v2
        with:
          cache: true

      # 3) Prépare Flutter
      - run: flutter clean
      - run: flutter pub get

      # 4) Code signing
      - name: Install codesign files
        run: |
          printf '%s' "$CERT_BASE64"    | base64 -d > cert.p12
          printf '%s' "$PROFILE_BASE64" | base64 -d > profile.mobileprovision
          CLEAN_PASS=$(printf '%s' "$CERT_PASSWORD" | tr -d '\r')
          security create-keychain -p "" build.keychain
          security import cert.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "$CLEAN_PASS" -A
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          CERT_BASE64:    ${{ secrets.CERT_BASE64 }}
          PROFILE_BASE64: ${{ secrets.PROFILE_BASE64 }}
          CERT_PASSWORD:  ${{ secrets.CERT_PASSWORD }}

      # 5) Build iOS
      - name: Build IPA
        run: flutter build ipa --export-options-plist=ios/ExportOptions.plist

      # 6) Récupère ton .ipa
      - uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa/*.ipa
