name: Build iOS  
on: [push]

jobs:
  build:
    runs-on: macos-14    # Xcode 15

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          cache: true

      # 3) Flutter prep
      - run: flutter clean
      - run: flutter pub get

      # 4) Create & unlock temporary keychain
      - name: Create temporary keychain
        run: |
          security create-keychain -p "" temp.keychain
          security default-keychain -s temp.keychain
          security unlock-keychain -p "" temp.keychain

      # 5) Import certificate & profile
      - name: Import cert & profile
        run: |
          # 5.1 decode base64 -> files
          echo "${{ secrets.CERT_BASE64 }}"    | base64 -D > cert.p12
          echo "${{ secrets.PROFILE_BASE64 }}" | base64 -D > profile.mobileprovision

          # 5.2 import into our keychain
          security import cert.p12 \
            -k ~/Library/Keychains/temp.keychain \
            -P "${{ secrets.CERT_PASSWORD }}" \
            -T /usr/bin/codesign

          # 5.3 install provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision \
             ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          # these 3 secrets you devez avoir créés dans Settings → Secrets
          CERT_BASE64:    ${{ secrets.CERT_BASE64 }}
          PROFILE_BASE64: ${{ secrets.PROFILE_BASE64 }}
          CERT_PASSWORD:  ${{ secrets.CERT_PASSWORD }}

      # 6) Build IPA (automatiquement codesigné)
      - name: Build IPA
        run: |
          flutter build ipa \
            --export-options-plist=ios/ExportOptions.plist

      # 7) Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa/*.ipa

      # 8) Cleanup
      - name: Cleanup temp keychain
        run: security delete-keychain temp.keychain
