name: Build iOS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # runner macOS gratuit pour dépôt public

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - run: flutter clean
      - run: flutter pub get

      - name: Install signing files
        run: |
          # 1) Décoder et écrire les fichiers
          echo "${{ secrets.CERT_BASE64 }}"    | base64 --decode > cert.p12
          echo "${{ secrets.PROFILE_BASE64 }}" | base64 --decode > profile.mobileprovision

          # 2) Importer le certificat dans le trousseau temporaire
          security create-keychain -p "" build.keychain
          security import cert.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "${{ secrets.CERT_PASSWORD }}" \
            -T /usr/bin/codesign

          # 3) Copier le provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision \
            ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: flutter build ipa \
          --export-options-plist=ios/ExportOptions.plist

      - uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa/*.ipa

      - name: Cleanup
        run: security delete-keychain build.keychain
